typography_spectrum: 0.6110985595732927
color:
  brandStrength: 0.8955842352006584
  lightness: 0.5495527242310345
  saturation: 0.5479324334301054
  rhythmicContrast: 0.29044182458892465
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.18666651262901723
name: THE ARTIVIST
navigation:
  - name: THE ARTIVIST
    url: 'https://soundcloud.com/the_artivist'
    type: external
title: Art&Activism
description: 'drawing the attention to global problems '
